private_registry:
  host: babel.ngc-data.fr:8443
  login: ppottie
  token: bYsV2EKMBu961kcyYyNn
url_domain: ngc-data.fr
prefix_url_domain: recette-
servers:
  # VM-PDDV-HAPROXY:
  #   name: VM-PDDV-HAPROXY
  #   type: haproxy
  #   box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
  #   eth1: 192.168.30.11
  #   mem: '2048'
  #   cpu: '2'
  #   forward_ports:
  #     - 80
  #     - 8080
  VM-PDDV-NGC-AUTO-DCK-BDD:
    name: VM-PDDV-NGC-AUTO-DCK-BDD
    type: postgres
    box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
    eth1: 192.168.30.12
    mem: '2048'
    cpu: '2'
  VM-PDDV-NGC-LAFA-DCK-BDD:
    name: VM-PDDV-NGC-LAFA-DCK-BDD
    type: mysql
    box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
    eth1: 192.168.30.23
    mem: '2048'
    cpu: '2'
  # VM-PDDV-NGC-METRICS:
  #   name: VM-PDDV-NGC-METRICS
  #   type: metrics
  #   box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
  #   eth1: 192.168.30.226
  #   mem: '2048'
  #   cpu: '2'
  #   os_version: debian buster
  VM-PDDV-NGC-ELK-MONIT:
    name: VM-PDDV-NGC-ELK-MONIT
    type: logs
    box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
    eth1: 192.168.30.25
    mem: '2048'
    cpu: '2'
  VM-PDDV-NGC-AUTO-DCK:
    name: VM-PDDV-NGC-AUTO-DCK
    type: swarm
    box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
    eth1: 192.168.30.13
    mem: '2048'
    cpu: '2'
  VM-PDDV-NGC-TRENT-DCK:
    name: VM-PDDV-NGC-TRENT-DCK
    type: swarm
    box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
    eth1: 192.168.30.27
    mem: '2048'
    cpu: '2'
  # VM-PDDV-NGC-DCK-ELK-1:
  #   vm_name: elk1
  #   type: cluster-elk
  #   box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
  #   eth1: 192.168.30.21
  #   mem: '2048'
  #   cpu: '2'
  # VM-PDDV-NGC-DCK-ELK-2
  #    vm_name: elk2
  #    type: cluster-elk
  #    box: ./packer_debian10-10G-vm-swarm-master-01_virtualbox.box
  #    eth1: 192.168.30.28
  #    mem: '1024'
  #    cpu: '1'

MANAGERS: 1
WORKERS: 1
ANSIBLE_GROUPS:
  # load-balancer:
  #   - VM-PDDV-HAPROXY
  managers:
    - VM-PDDV-NGC-AUTO-DCK
  workers:
    - VM-PDDV-NGC-TRENT-DCK
  databases-postgresql:
    - VM-PDDV-NGC-AUTO-DCK-BDD
  databases-mysql-docker:
    - VM-PDDV-NGC-LAFA-DCK-BDD
  gluster:
    - VM-PDDV-NGC-AUTO-DCK
    - VM-PDDV-NGC-TRENT-DCK
  elk-logs:
    - VM-PDDV-NGC-ELK-MONIT
  elk-apm:
    - VM-PDDV-NGC-ELK-MONIT
  # metrics:
  #   - VM-PDDV-NGC-METRICS
  # elk:
  #   - 'VM-PDDV-NGC-DCK-ELK-[1:2]'
  'all_groups:children':
    - managers
    - workers
    - databases-postgresql
    - databases-mysql-docker
    - metrics
    - elk-logs
    - elk-apm
    - shares
