version: "3.7"
networks: 
  default:
    external: true
    name: internal-fluentd
services:
  fluentd-elasticsearch:
    image: babel.ngc-data.fr:8443/common/docker/fluentd:v1.13
    environment:
      FLUENTD_CONF: 'fluent.conf'
      FLUENTD_HOSTNAME: "{{ NODE_HOSTNAME }}"

    ports:
      - 24224:24224
      - 24224:24224/udp
    user: root
    volumes:
      - "{{ GLUSTER_MANAGER_PATH }}{{ PROJECT_NAME }}/config/fluentd.conf:/fluentd/etc/fluent.conf"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
  