- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  tasks:
  ### Build instances
    - file: path=log state=directory mode=0755

    - name: clean output directory
      file: path='./packer/output-debian_10' state=absent


    - name: create box vm
      shell: bash -c "packer build -var 'disk_size={{ item.size }}' -var 'name={{ item.name }}' -on-error=cleanup packer/debian-10-template.json " > log/debian10-{{ item.name }}.log
      args:
        creates: output-debian10-{{ item.size }}G-{{ item.name }}
      with_items:
        - { name: "vm-swarm-master-01", size: "10"}
      register: packer

    - name: create infra local virtual machines
      shell: bash -c "vagrant up" > log/infra.log

    - name: include local config
      include_vars:
        file: configs/vm-local/vars.vagrantfile.yaml
        name: environment

    - name: Update the /etc/hosts file with node name
      tags: etchostsupdate
      become: yes
      become_user: root
      lineinfile:
        path: "/etc/hosts"
        regexp: ".*\t{{ item['eth1']}}\t{{ item['name']}}"
        line: "{{ item[['eth1'] }}\t{{ item['name'] }}"
        state: present
        backup: yes
      register: etchostsupdate
      with_items: "{{environment[servers]}}"