version: "3.9"

services:
  node-exporter:
    image: "babel.ngc-data.fr:8443/common/docker/node-exporter:{{ VERSION }}"
    hostname: node-exporter
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    environment:
      - "NODE_ID={{ NODE_ID }}"
      - "NODE_NAME={{ NODE_NAME }}"
    logging:
      driver: fluentd
      options:
        tag: docker.monitoring.node-exporter
        fluentd-async-connect: "true"
    volumes:
      # Remember to use read-only bind mounts.
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs" # Necessary for collecting host filesystem metrics.
      - "--collector.textfile.directory=/etc/node-exporter"
      - "--collector.filesystem.ignored-mount-points='^/(sys|proc|dev|host|etc)($$|/)'"
      - '--no-collector.ipvs'
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      mode: global
      update_config: # Need for mode: host (line 11)
        order: stop-first

      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

# This listens to port 9100 ON THE HOST.
# This container does not have its own IP address.
# Binding to the host is necessary for node-exporter to collect accurate
# networking statistics about the host.
networks:
  default:
    external: true
    name: internal-monitoring