version: "3.7"

volumes:
  portainerdata: 

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik-proxy:
    external: true
    name: traefik-proxy
    
services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  
  portainer:
    image: "portainer/portainer-ce:{{ PORTAINER_VERSION }}"
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - traefik-proxy
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.portainer.rule=Host(`{{ PREFIX_URL_DOMAIN }}portainer.{{ URL_DOMAIN }}`)"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.routers.portainer.entrypoints=web"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
