version: "3.7"
networks:
  default:
    external: true
    name: internal-monitoring
  traefik-proxy:
    external: true
    name: traefik-proxy
services:
  alertmanager:
    image: "{{ ALERTMANAGER_DOCKER_URL }}:{{ ALERTMANAGER_VERSION }}"
    volumes:
      - ./configuration.yml:/etc/alertmanager/config.yml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config: # Need for mode: host 
        order: stop-first
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-proxy
        - traefik.http.routers.alertmanager.rule=Host(`{{ PREFIX_URL_DOMAIN }}alertmanager.{{ URL_DOMAIN }}`)
        - traefik.http.routers.alertmanager.entrypoints=web
        - traefik.http.services.alertmanager.loadbalancer.server.port=9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    
