version: '3.7'
networks:
  default:
    external: true
    name: internal-monitoring

services:
  # Using nginx to proxy prometheus access to docker daemon of node
  docker-exporter:
    image: nginx
    ports:
      - target: 80
        published: 9324
        protocol: tcp
        mode: host
    volumes:
      - /mnt/glusterfs/docker-exporter/nginx-docker-exporter:/etc/nginx/conf.d/default.conf
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 64M