
- hosts: managers[0]
  tasks:
    - name: Create internal monitoring network
      community.docker.docker_network:
        name:  internal-monitoring
        driver: overlay
        attachable: true
        state: present


#installation d'un service dans le cluster
- hosts: managers[0]
  roles:
    - visualizer
    - cadvisor
    - node-exporter
    - docker-exporter 
    - prometheus
    - grafana

