private_registry:
  host: babel.ngc-data.fr:8443
  login: ppottie
  token: bYsV2EKMBu961kcyYyNn
url_domain: ngc-data.fr
prefix_url_domain: recette-
servers:
  PDDV-NGC-AUTO-DCK-BDD:
    name: PDDV-NGC-AUTO-DCK-BDD
    eth1: 10.66.30.12
  PDDV-NGC-LAFA-DCK-BDD:
    name: PDDV-NGC-LAFA-DCK-BDD
    eth1: 10.66.30.23
  PDDV-NGC-ELK-MONIT:
    name: PDDV-NGC-ELK-MONIT
    eth1: 10.66.30.25
  PDDV-NGC-AUTO-SWARM-M:
    name: PDDV-NGC-AUTO-SWARM-M
    eth1: 10.66.30.29
  PDDV-NGC-AUTO-SWARM-N1:
    name: PDDV-NGC-AUTO-SWARM-N1
    eth1: 10.66.30.33
  PDDV-NGC-AUTO-SWARM-N2:
    name: PDDV-NGC-AUTO-SWARM-N2
    eth1: 10.66.30.34
