GLUSTER_SHARE_PATH: /mnt/shared_datas/
GLUSTER_MANAGER_PATH: /mnt/manager_deploy/
GLUSTER_MONITORING_PATH: /mnt/monitoring/
username: "{{ ansible_user }}"
world: prod
private_registry:
  host: babel.ngc-data.fr:8443
  login: ppottie
  token: bYsV2EKMBu961kcyYyNn
URL_DOMAIN: ngc-data.fr
PREFIX_URL_DOMAIN: pra-
servers:
