
# Deploy project
- hosts: managers[0]
  roles:
    - { role: "network",  PROJECT_NAME: "prospects",PROJECT_SERVICE_NAME: "api"}
    - { role: "api" , PROJECT_NAME: "prospects",PROJECT_SERVICE_NAME: "api", SECRETS: "../../../../../../configs/{{ world }}/prospects/api/vars.yml" , CONFIG_DEPLOY: "{{ CONFIG_PROSPECTS['api'] }}"}
