- include: postgresql.yml
  when: world == "vm-local"
  

# create overlay networks
- hosts: managers[0]
  roles:
    - network

# Deploy project
- hosts: managers[0]
  roles:
    - { role: "networks" , GLOBAL_PROJECT_NAME: "prospects" , GLOBAL_SERVICE_NAME: api}
    - { role: "api" ,  GLOBAL_PROJECT_NAME: "prospects", GLOBAL_SERVICE_NAME: api, SERCRETS: "../../../../../../configs/{{ world }}/prospects/vars.yml"  }

