
- name: Create internal fluentd network
  community.docker.docker_network:
    name:  internal-fluentd
    driver: overlay
    attachable: true
    state: present


- name: "Create a directory {{ PROJECT_NAME }} on gluster volume for manager nodes"
  file:
    path: "{{ GLUSTER_MANAGER_PATH }}{{ item }}"
    state: directory
    owner: "{{ PROJECT_USER }}"
    group: "{{ PROJECT_USER }}"
  loop:
    - "{{ PROJECT_NAME }}"
    - "{{ PROJECT_NAME }}/config"



- name: Generate config file fluentd.conf  
  template:
    src: "./templates/config/fluentd.conf"
    dest: "{{ GLUSTER_MANAGER_PATH }}{{ PROJECT_NAME }}/config/fluentd.conf"
    owner: "{{ PROJECT_USER }}"
    group: "{{ PROJECT_USER }}"
    force: true

- name: Generate docker-compose.yml  files to master
  template:
    src: "./templates/docker-compose.yml"
    dest: "{{ GLUSTER_MANAGER_PATH }}{{ PROJECT_NAME }}/{{ PROJECT_NAME }}-compose.yml"
    owner: "{{ PROJECT_USER }}"
    group: "{{ PROJECT_USER }}"
    force: true


- community.docker.docker_stack:
    name: "{{ PROJECT_NAME }}"
    state: absent 

- name: "deploy {{ PROJECT_NAME }} stack"
  community.docker.docker_stack:
    state: present
    name: "{{ PROJECT_NAME }}"
    with_registry_auth: yes
    compose:
      - "{{ GLUSTER_MANAGER_PATH }}{{ PROJECT_NAME }}/{{ PROJECT_NAME }}-compose.yml"