

- name: "Create {{ PROJECT_NAME }} directories"
  file:
    path: "{{ GLUSTER_SHARE_PATH }}/{{ item }}"
    state: directory
  loop:
    - "{{ PROJECT_NAME }}/"    
    - "{{ PROJECT_NAME }}/{{ PROJECT_SERVICE_NAME }}"
    - "{{ PROJECT_NAME }}/{{ PROJECT_SERVICE_NAME }}/data"

- name: "Generate docker-compose.yml file"
  template:
    src: "./templates/docker-compose.yml"
    dest: "{{ GLUSTER_MANAGER_PATH }}/{{ PROJECT_NAME }}/{{ PROJECT_SERVICE_NAME }}-compose.yml"
    owner: "{{ PROJECT_USER }}"
    group: "{{ PROJECT_USER }}"
    force: true

- name: "Deploy {{ PROJECT_NAME }}{{ PROJECT_SERVICE_NAME }} stack"
  community.docker.docker_stack:
    state: present
    name: "{{ PROJECT_NAME }}-{{ PROJECT_SERVICE_NAME }}"
    prune: true
    with_registry_auth: yes
    compose:
      - "{{ GLUSTER_MANAGER_PATH }}/{{ PROJECT_NAME }}/{{ PROJECT_SERVICE_NAME }}-compose.yml"
