APP_XDEBUG: disabled
PUBLIC_SHARED: enabled
UPLOAD_SHARED: enabled
API_URL: http://api/api
APP_ENV: prod
SENTRY_DSN: ${SENTRY_DSN}
SENTRY_ENVIRONMENT: ${SENTRY_ENV}
REDIS_HOST: redis
GULP_HTTP_DOMAIN: https://plateforme.autoviza.fr
REDIS_PORT: '6379'
REDIS_DB: ${REDIS_DB}
REDIS_SESSION_DB: ${REDIS_SESSION_DB}
JWT_PRIVATE_KEY_PATH: config/jwt/private.pem
JWT_PUBLIC_KEY_PATH: config/jwt/public.pem
JWT_PASSPHRASE: autoviza
JWT_TOKEN_TTL: 43200
LOGIN_PAGE: disabled

REDIS_DB: '5'
REDIS_SESSION_DB: '6'
SENTRY_ENV: staging
SENTRY_DSN: https://bd6b3365c2314c25ad339dbf1214bd76@o223249.ingest.sentry.io/3459128?environment=${SENTRY_ENV}&release=${VERSION}
SECURITY_TOKEN: XRLeteqbKbZVFNDAdRvNfvVthsHbCWcvrwnn9evs4AWEuADvnYHVGnCYJojxaS77
STATUS_TOKEN: 1b88a8e0571813f16a2b4e4aeb0e23a7

VERSION: "{{ FRONT_VERSION }}"