

- name: Create a visualizer directory's
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ visualizer_user }}"
    group: "{{ visualizer_user }}"
  with_items:
    - "{{ visualizer_home }}"


- name: Template a file to visualizer-compose.yml
  template:
    src: "./templates/{{ item }}"
    dest: "{{ visualizer_home }}/{{ item }}"
    owner: "{{ visualizer_user }}"
    group:  "{{ visualizer_user }}"
    mode: '0644'
  loop:
    - visualizer-compose.yml

- community.docker.docker_stack:
    name: visualizer
    state: absent

- name: deploy visualizer service
  community.docker.docker_stack:
    state: present
    name: visualizer
    with_registry_auth: yes
    compose:
      - "{{ visualizer_home }}/visualizer-compose.yml"
