version: "3.7"
networks:
  default:
    external:
      name: "{{ PROJECT_NAME }}-{{ PROJECT_SERVICE_NAME }}"

volumes:
  redis_data:
    driver: "local"
    driver_opts: 
      o: "bind"
      device: "{{ GLUSTER_SHARE_PATH }}/{{ PROJECT_NAME }}/{{ PROJECT_SERVICE_NAME }}/data"
      type: "glusterfs"
services:
  redis:
    image: babel.ngc-data.fr:8443/common/docker/redis:{{ REDIS_VERSION }}
    hostname: "{{ PROJECT_NAME }}-{{ PROJECT_SERVICE_NAME }}.{{ NODE_HOSTNAME }}"
    deploy:
      replicas: 1
      restart_policy:
        condition: "any"
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.15"
          memory: "20M"
    healthcheck:
      test: "redis-cli ping"
      interval: "20s"
      timeout: "10s"
      retries: 3
    logging:
      driver: "fluentd"
      options:
        tag: "docker.{{ PROJECT_NAME }}.{{ PROJECT_SERVICE_NAME }}"
        fluentd-async-connect: "true"
    volumes:
      - "redis_data:/data"


    
