
- hosts: databases-postgresql
  become: yes
  become_user: root
  roles:
    - postgresql

- hosts: databases-postgresql
  become: yes
  become_method: sudo
  become_user: postgres
  roles:
    - database

- hosts: managers[0]
  become: yes
  become_user: root
  roles:
    - network


- hosts: managers[0]
  roles:
    - api-kilometer

