
# General
# ------------------------------------------------------------------------------ 

USE_DOCKER: yes
IPYTHONDIR: /app/.ipython

# django-accounts
# ------------------------------------------------------------------------------
UNIQUE_CONNECTION: False

# django-consumption
# ------------------------------------------------------------------------------
CONSUMPTION_IDENTITY_FIELD: username
CONSUMPTION_QUOTA_ADMIN_FILTER_FIELD: username

# django-swagger
# ------------------------------------------------------------------------------
PROJECT_NAME: kilometers
PROJECT_SHORT_DESCRIPTION: "Kilometers REST API for NGC."



# app
# ------------------------------------------------------------------------------
ADMIN_PANEL: True
DJANGO_DEBUG: True
DJANGO_ALLOWED_HOSTS: "localhost,{{ PROJECT_URL_DOMAIN | default('') }}"
DJANGO_SECURE_SSL_REDIRECT: False
DJANGO_SECURE_HSTS_PRELOAD: False
DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: False
DJANGO_CSRF_COOKIE_SECURE: False

# databases
# ------------------------------------------------------------------------------
# LAFACOMMUN PREPROD
DATABASE_LAFA_COMMUN_NAME: lafa_commun
DATABASE_LAFA_COMMUN_USER: ngc
DATABASE_LAFA_COMMUN_PASSWORD: Ngc@MariaDB@2019
DATABASE_LAFA_COMMUN_HOST: "{{ LAFA_COMMON_HOST | default('')}}"
DATABASE_LAFA_COMMUN_PORT: 3306

# Redis
# ------------------------------------------------------------------------------
REDIS_URL: redis://redis:6379/0

# APM
# ------------------------------------------------------------------------------
ELASTIC_APM_ENABLED: True
APM_URL: "{{ APM_URL | default('') }}"
APM_SECRET_TOKEN:
# PostgreSQL
# ------------------------------------------------------------------------------
POSTGRES_HOST: "{{ POSTGRESQL_HOST | default('')}}"
POSTGRES_PORT: 5432
POSTGRES_DB: kilometers-api
POSTGRES_USER: api
POSTGRES_PASSWORD: koh6Phodiyooh3seetoh

COMPRESS_ENABLED: true
DJANGO_SECRET_KEY: o8EHQCgFpZqiHuQ1W06MVhUcuSQPWGtJ99IeYZaeTiqLTkmn
MAILJET_API_KEY: 
MAILJET_SECRET_KEY: 

SENTRY_DSN: 
SENTRY_ENVIRONMENT: 
PROJECT_ENVIRONMENT: 
