
ADMIN_PANEL: "True"
SECRET_KEY: LuaGQjCCOJrMBQYEmV145GMaXHSEwpP1gnXPsKykcGLCsEHQ
DEBUG: "False"
HOST_LOCALHOST: "0.0.0.0"
HOST_LOCALHOST_FQDN: localhost
HOST_IP:
HOST_FQDN: "{{ PROJECT_URL_DOMAIN }}"
LOGGING_LEVEL: INFO
SENTRY_DSN:
SENTRY_ENVIRONMENT:
### DATABASES
# DEFAULT
DATABASE_DEFAULT_NAME: kilometers-api
DATABASE_DEFAULT_USER: api
DATABASE_DEFAULT_PASSWORD: koh6Phodiyooh3seetoh
DATABASE_DEFAULT_HOST: "{{ POSTGRESQL_HOST }}"
DATABASE_DEFAULT_PORT: 5432
# LAFA_COMMUN
DATABASE_LAFA_COMMUN_NAME: lafa_commun
DATABASE_LAFA_COMMUN_USER: ngc
DATABASE_LAFA_COMMUN_PASSWORD: Ngc@MariaDB@2019
DATABASE_LAFA_COMMUN_HOST: "{{ LAFA_COMMON_HOST }}"
DATABASE_LAFA_COMMUN_PORT: 3306
# REDIS
REDIS_CACHE_LOCATION: redis://redis:6379/0