

- name: Create List of master nodes to be added into Cluster
  set_fact:
    nodelist: "{{ groups[GROUP_NODE]|map('extract', servers, 'eth1')|list }}"


- name: Show the list we obtained for ansible_all_ipv4_addresses
  debug: msg="{{nodelist}}"


- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ GLUSTER_BRICK_DIR }}"
    - "{{ GLUSTER_MOUNT_DIR }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ GLUSTER_BRICK_NAME }}"
    brick: "{{ GLUSTER_BRICK_DIR }}"
    rebalance: yes
    cluster: "{{ nodelist }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ MASTER_SHARE_BRICK_NAME }}"
    brick: "{{ MASTER_SHARE_BRICK_DIR }}"
    rebalance: yes
    cluster: "{{ nodelist }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true


- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ GLUSTER_MOUNT_DIR }}"
    src: "{{ inventory_hostname }}:/{{ GLUSTER_BRICK_NAME }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
    boot: yes

- name: directory permissions
  file:
    path: "{{ GLUSTER_MOUNT_DIR }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775
    recurse: yes
  become: yes
