---
- include: config_docker_daemon.yml
  when: world == "vm-local"

# lecture de l'état du swarm sur le noeud du cluster
- hosts: workers[-1]
  tasks:
    - name: Log into private registry and force re-authorization
      community.docker.docker_login:
        registry_url: "{{ private_registry.host }}"
        username: "{{ private_registry.login }}"
        password: "{{ private_registry.token }}"
        reauthorize: yes

- hosts: workers[-1]
  tasks:
    - name: Check if Swarm Mode is already activated
      command: docker info
      register: docker_info
      changed_when: false

# Recupere le worker token sur le manageur principal
- hosts: managers[0]
  tasks:
    - name: Retrieve worker token
      shell: >
        docker swarm join-token worker --quiet
      register: worker_token_result

    - set_fact:
        worker_token: "{{ worker_token_result.stdout }}"
        primary_manager_ip: "{{ vagrant_primary_manager_ip | default(ansible_default_ipv4.address) }}"



# rejoindre le cluser pour les machines workers
- hosts: workers[-1]
  tasks:
    - name: Starting swarm workers to join cluster
      shell: >
        docker swarm join \
          --token {{ hostvars[groups['managers'][0]]['worker_token']  }} \
          {{  hostvars[groups['managers'][0]]['primary_manager_ip'] }}:{{ swarm_bind_port | default('2377')}}
      register: init_result
      when: '"Swarm: active" not in docker_info.stdout'
