---

- hosts: managers,workers
  become: yes
  become_user: root
  tasks:
    - name: Ensure json file exists
      copy:
        content: "{}"
        dest: /etc/docker/daemon.json
        force: false

  
    - name: append more key/values
      set_fact:
        docker_vars: "{{ docker_vars | default([]) | combine({ item.key : item.value }) }}"
      with_items:
      - { key: "log-driver", value: "json-file" }
      - { key: "log-opts", value: { max-size: "10m", max-file: "3"} }
      - { key: "metrics-addr", value: "0.0.0.0:9323" }
      - { key: "experimental", value: true }

    - debug:
        var: docker_vars

    - name: write var to file
      copy:
        content: "{{ docker_vars | to_nice_json }}"
        dest: /etc/docker/daemon.json

    - name: Restart service docker daemon
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: docker
