- hosts: managers, workers, databases-mysql-docker
  become: yes
  become_user: root
  vars:
  tasks:

    - name: update pip3 to setup ansible <---> docker
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: update docker dsk && jsondiff
      pip:
        name: "{{item}}"
      loop:
      - docker
      - jsondiff

    - name: install docker-compose
      apt:
        name: "{{item}}"
        state: latest
        force_apt_get: yes
        update_cache: yes
      loop:
        - docker-compose