- hosts: managers, workers, databases-mysql, elk-apm
  become: yes
  become_user: root
  vars:
    DOCKER_COMPOSE_VERSION: 1.29.1
  tasks:

    - name: update pip3 to setup ansible <---> docker
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: update docker sdk && jsondiff
      pip:
        name: "{{item}}"
      loop:
      - docker
      - jsondiff
      - docker-compose

    - name: download docker-compose
      command: curl -s -L "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

    - name: set executable permission on docker-compose binary
      file:
        path: /usr/local/bin/docker-compose
        mode: 0755
