---

- hosts: databases[0]
  become: yes
  become_user: root
  tasks:

    - name: Add key for Postgres repo
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present


    - name: Add Postgres repo to sources list
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' state=present


- hosts: databases[0]
  become: yes
  become_user: root
  tasks:

    - name: Install required system packages
      apt: name={{ item }} state=present update_cache=yes force_apt_get=yes
      loop: 
        - libicu-dev
        - software-properties-common
        - libpq-dev
        - python-psycopg2
        - postgresql-contrib-11
        - sysstat
        - postgresql-11



- hosts: databases[0]
  become: yes
  become_user: root
  gather_facts: no

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

  tasks:
    - name: postgresql should listen on all ports
      lineinfile: dest=/etc/postgresql/11/main/postgresql.conf
                  regexp="^listen_addresses"
                  line="listen_addresses = '*'" state=present

    - name: postgresql should allow access to host
      copy:
        dest: /etc/postgresql/11/main/pg_hba.conf
        content: |
          local   all   postgres   peer
          local   all   all        peer
          host    all   all        0.0.0.0/0   md5
      notify: restart postgresql
