---

- hosts: databases-postgresql
  become: yes
  become_user: root
  tasks:

    - name: Add key for Postgres repo
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present


    - name: Add Postgres repo to sources list
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' state=present


- hosts: databases-postgresql
  become: yes
  become_user: root
  tasks:

    - name: Install required system packages
      apt: name={{ item }} state=present update_cache=yes force_apt_get=yes
      loop:
        - libicu-dev
        - software-properties-common
        - libpq-dev
        - python3-psycopg2
        - postgresql-contrib-11
        - sysstat
        - postgresql-11

- hosts: databases-postgresql
  become: yes
  become_user: root
  gather_facts: no

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

  tasks:
    - name: postgresql should listen on all ports
      lineinfile: dest=/etc/postgresql/11/main/postgresql.conf
                  regexp="^listen_addresses"
                  line="listen_addresses = '*'" state=present
      notify: restart postgresql